### ISSUE TITLE
这个方法貌似已经失效了

### ISSUE THREAD

**Issue by 960208781** [badyun/AShare#5]
![image](https://user-images.githubusercontent.com/23545692/119924806-d8572c00-bfa6-11eb-8fb9-4ae9700fd2f3.png)

**Comment by badyun** [comment]
使用手机app的token


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "badyun/AShare"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 中午11:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[badyun/AShare] 这个方法貌似已经失效了 (#5)
